# Generated by Django 3.0.3 on 2020-02-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0003_auto_20200219_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishmodel',
            name='desc',
        ),
        migrations.AddField(
            model_name='wishmodel',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
