# Generated by Django 3.0.3 on 2020-02-19 21:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0004_auto_20200219_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='wishmodel',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
