# Generated by Django 3.0.3 on 2020-02-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0005_auto_20200219_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishmodel',
            name='UUID',
        ),
        migrations.AddField(
            model_name='wishmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
