# Generated by Django 3.0.3 on 2020-02-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0006_auto_20200220_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishmodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
