# Generated by Django 3.0.3 on 2020-02-20 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0007_wishmodel_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='wishmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
